function pc_2 = auto_pc_back(th)
%AUTO_PC_BACK
%    PC_2 = AUTO_PC_BACK(TH)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    10-Dec-2019 19:24:54

t2 = pi./6.0;
t3 = t2+th;
pc_2 = [th.*(6.3e+1./1.0e+2)+sin(t3).*(6.3e+1./1.0e+2)+6.3e+1./2.0e+2;cos(t3).*(6.3e+1./1.0e+2)+6.3e+1./1.0e+2];
