function pball = auto_p_ball(th)
%AUTO_P_BALL
%    PBALL = AUTO_P_BALL(TH)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    10-Dec-2019 19:24:57

pball = [th.*(6.3e+1./1.0e+2)+6.3e+1./2.0e+2;6.3e+1./1.0e+2];
