function J_bc_back = auto_J_bc_back(th)
%AUTO_J_BC_BACK
%    J_BC_BACK = AUTO_J_BC_BACK(TH)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    10-Dec-2019 19:24:54

t2 = pi./6.0;
t3 = t2+th;
J_bc_back = [cos(t3).*(6.3e+1./1.0e+2)+6.3e+1./1.0e+2;sin(t3).*(-6.3e+1./1.0e+2)];
