function pc_1 = auto_pc_front(th)
%AUTO_PC_FRONT
%    PC_1 = AUTO_PC_FRONT(TH)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    10-Dec-2019 19:24:54

t2 = pi./6.0;
t3 = -t2;
t4 = t3+th;
pc_1 = [th.*(6.3e+1./1.0e+2)+sin(t4).*(6.3e+1./1.0e+2)+6.3e+1./2.0e+2;cos(t4).*(6.3e+1./1.0e+2)+6.3e+1./1.0e+2];
