function dJback = auto_dJ_backToe(in1,in2)
%AUTO_DJ_BACKTOE
%    DJBACK = AUTO_DJ_BACKTOE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    10-Dec-2019 18:33:50

dq3 = in2(3,:);
dq6 = in2(6,:);
dq7 = in2(7,:);
q3 = in1(3,:);
q6 = in1(6,:);
q7 = in1(7,:);
t2 = q3+q6;
t3 = cos(t2);
t4 = q7+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = sin(t4);
t8 = t3.*(2.0./5.0);
t9 = t5.*(2.0./5.0);
t10 = t6.*(2.0./5.0);
t11 = t7.*(2.0./5.0);
t14 = dq7.*t6.*(-2.0./5.0);
t15 = dq7.*t7.*(-2.0./5.0);
t12 = dq7.*t10;
t13 = dq7.*t11;
t16 = t8+t10;
t17 = t9+t11;
t18 = dq6.*t16;
t19 = dq6.*t17;
t20 = -t18;
t21 = -t19;
dJback = reshape([0.0,0.0,0.0,0.0,t15+t21-dq3.*(t17+sin(q3).*(6.3e+1./1.0e+2)),t14+t20-dq3.*(t16+cos(q3).*(6.3e+1./1.0e+2)),0.0,0.0,0.0,0.0,t15+t21-dq3.*t17,t14+t20-dq3.*t16,t15-dq3.*t7.*(2.0./5.0)-dq6.*t7.*(2.0./5.0),t14-dq3.*t6.*(2.0./5.0)-dq6.*t6.*(2.0./5.0)],[2,7]);
