function J_bc_front = auto_J_bc_front(th)
%AUTO_J_BC_FRONT
%    J_BC_FRONT = AUTO_J_BC_FRONT(TH)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    10-Dec-2019 19:24:54

t2 = pi./6.0;
t3 = -t2;
t4 = t3+th;
J_bc_front = [cos(t4).*(6.3e+1./1.0e+2)+6.3e+1./1.0e+2;sin(t4).*(-6.3e+1./1.0e+2)];
