function dJ_bc_front = auto_dJ_bc_front(th,dth)
%AUTO_DJ_BC_FRONT
%    DJ_BC_FRONT = AUTO_DJ_BC_FRONT(TH,DTH)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    10-Dec-2019 19:24:54

t2 = pi./6.0;
t3 = -t2;
t4 = t3+th;
dJ_bc_front = [dth.*sin(t4).*(-6.3e+1./1.0e+2);dth.*cos(t4).*(-6.3e+1./1.0e+2)];
