function p_leg2 = auto_p_backToe(in1)
%AUTO_P_BACKTOE
%    P_LEG2 = AUTO_P_BACKTOE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    10-Dec-2019 13:33:47

q3 = in1(3,:);
q6 = in1(6,:);
q7 = in1(7,:);
x = in1(1,:);
y = in1(2,:);
t2 = q3+q6;
t3 = q7+t2;
p_leg2 = [x+sin(q3).*(6.3e+1./1.0e+2)+sin(t2).*(2.0./5.0)+sin(t3).*(2.0./5.0);y+cos(q3).*(6.3e+1./1.0e+2)+cos(t2).*(2.0./5.0)+cos(t3).*(2.0./5.0)];
