function dJ_bc_back = auto_dJ_bc_back(th,dth)
%AUTO_DJ_BC_BACK
%    DJ_BC_BACK = AUTO_DJ_BC_BACK(TH,DTH)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    10-Dec-2019 19:24:54

t2 = pi./6.0;
t3 = t2+th;
dJ_bc_back = [dth.*sin(t3).*(-6.3e+1./1.0e+2);dth.*cos(t3).*(-6.3e+1./1.0e+2)];
