function dJfront = auto_dJ_frontToe(in1,in2)
%AUTO_DJ_FRONTTOE
%    DJFRONT = AUTO_DJ_FRONTTOE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    10-Dec-2019 18:33:49

dq3 = in2(3,:);
dq4 = in2(4,:);
dq5 = in2(5,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
t2 = q3+q4;
t3 = cos(t2);
t4 = q5+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = sin(t4);
t8 = t3.*(2.0./5.0);
t9 = t5.*(2.0./5.0);
t10 = t6.*(2.0./5.0);
t11 = t7.*(2.0./5.0);
t14 = dq5.*t6.*(-2.0./5.0);
t15 = dq5.*t7.*(-2.0./5.0);
t12 = dq5.*t10;
t13 = dq5.*t11;
t16 = t8+t10;
t17 = t9+t11;
t18 = dq3.*t16;
t19 = dq4.*t16;
t20 = dq3.*t17;
t21 = dq4.*t17;
t22 = -t18;
t23 = -t19;
t24 = -t20;
t25 = -t21;
t26 = t14+t22+t23;
t27 = t15+t24+t25;
dJfront = reshape([0.0,0.0,0.0,0.0,t27,t26,t27,t26,t15-dq3.*t7.*(2.0./5.0)-dq4.*t7.*(2.0./5.0),t14-dq3.*t6.*(2.0./5.0)-dq4.*t6.*(2.0./5.0),0.0,0.0,0.0,0.0],[2,7]);
