function J_back = auto_J_backToe(in1)
%AUTO_J_BACKTOE
%    J_BACK = AUTO_J_BACKTOE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    10-Dec-2019 18:33:49

q3 = in1(3,:);
q6 = in1(6,:);
q7 = in1(7,:);
t2 = q3+q6;
t3 = cos(t2);
t4 = q7+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = sin(t4);
t8 = t3.*(2.0./5.0);
t9 = t5.*(2.0./5.0);
t10 = -t9;
t11 = t6.*(2.0./5.0);
t12 = t7.*(2.0./5.0);
t13 = -t12;
J_back = reshape([1.0,0.0,0.0,1.0,t8+t11+cos(q3).*(6.3e+1./1.0e+2),t10+t13-sin(q3).*(6.3e+1./1.0e+2),0.0,0.0,0.0,0.0,t8+t11,t10+t13,t11,t13],[2,7]);
